### ISSUE TITLE
Support for Krypton?

### ISSUE THREAD

**Issue by shyim** [gaining/Kissanime-fork#1]
Hey,

have you any plans to support also Krypton version?

**Comment by gaining** [comment]
I found out about kodi 2 months ago, didn't even know if krypton was the next version until today but I'll take a looks in their api changes to see if that's feasible.

**Comment by magearden** [comment]
+ 1 for Krypton support, also thanks for the patch :) works brilliantly ;)

**Comment by DarkLordVal** [comment]
Yeah please see if krypton support is possible

**Comment by DarkLordVal** [comment]
No updates on this?

**Comment by gaining** [comment]
I did take a quick look and it looks like few existing functions will need to be modified to be compatible with Kodi 17.  I have been in Cuba for a weeks so I haven't been able to work on it much. Just got back to Canada today. When there's an update, you will know as I make new commits and Happy new year 👍

**Comment by DarkLordVal** [comment]
Thank you! Happy New Years to you as well!

**Comment by gaining** [comment]
I'm very close to bring kissanime to kodi 17. I should be done by tonight or tomorrow morning.

**Comment by gaining** [comment]
Added kodi 17 support. The newest addon should now work with kodi 17.

**Comment by magearden** [comment]
Awesome 👏🏻 thanks for adding support for Krypton (tested it and its working great) again thanks 🙏🏻

**Comment by DarkLordVal** [comment]
Sorry to bother, thanks for adding support, but is there a specific way I have to get it? I try getting it from super retro, and no luck it never downloads :/, as I missing something?

**Comment by DarkLordVal** [comment]
Nvm, I got it thanks, downloaded to USB from px and connected to amazon tv. Thanks!!!

**Comment by gaining** [comment]
It's in the tv addons repo.
