### ISSUE TITLE
Video Playback is broken in the addon

### ISSUE THREAD

**Issue by gaining** [gaining/Kissanime-fork#2]
Videos in the kissanime website are using new encryption mechanisms. I have a workaround in mind that I'll try to implement bypassing the encryption altogether. If test succeeds I'll update the add-on.

**Comment by magearden** [comment]
Thanks man ;) hope it succeeds I really need my anime fix :) *crosses fingers*

**Comment by Crashdummyy** [comment]
Any News ?

**Comment by gaining** [comment]
I'll give a conclusive update this weekend. I'm only free on weekends to work on this but last week wasn't enough.

**Comment by gaining** [comment]
Someone, _dat1guy_ , has a conceivable fix for the addon, I've requested permission to implement it in this repository. Originally I wanted to use **beautifulsoup** and **request** python libraries to try and fix the addon avoiding encryption. That way, the addon would not break when kissanime change the encryption again since it would be accessing the videos similar to a web browser. For that to happen, I'd need to rewrite a lot of the core parts on how the addon processes html data. That would take time since I'd need to learn how but I will be doing regardless because preliminary tests were successful and it's an interesting study.

**Comment by gaining** [comment]
I noticed dat1guy's addon uses the gpl liscence so I went ahead and used his fix to fix the addon. Of course credited him and prometheusx for fixing it. New addon is ready for download

**Comment by rebellionist** [comment]
Thank you, testing right now CONFIRMED WORKING no issues, your an absolute legend

**Comment by xXFearTheGuestX** [comment]
When I try to install on Kodi 17 I get an error that says "could not install from Zip file" what am I doing wrong?

**Comment by gaining** [comment]
@xXFearTheGuestX , you should try again, I've re-uploaded the zip when that problem occurred few hours ago. Anyways, tv addons are going to update their addon to this version soon like they did before. If you want, you could wait for later today or Monday.

**Comment by neoexploda** [comment]
Hi Gaining,

Thank you for the continuous contribution.

There really a problem with the fix march 2017 zip file you uploaded.

Please check and re upload again in your free time.

**Comment by gaining** [comment]
@neoexploda  I've re-uploaded again.

**Comment by gaining** [comment]
I re-uploaded, please try again.


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by djneo0** [comment]
It working great!. Thanks a lot for your contribution

**Comment by gaining** [comment]
Glad it's working for you. Credit also goes to dat1guy and prometheusx for this fix.

**Comment by xXFearTheGuestX** [comment]
Hi Gaining, I tried again and I'm still getting the same error.

**Comment by neoexploda** [comment]
Hi Gaining, thanks for uploading the plugin.video.kissanime-March2017fixes.

Install on my Kodi 17 but still the video won't load. I check the logviewer, it stated that : metahandler: Error connecting TBDB: Http Error 401: Unauthorized.

If i login with kissanime account, it get another set of error : Get directory Error getting plugin ...

**Comment by gaining** [comment]
The log doesn't really say much, the tmdb error means that the API key for TMDB that the plugin is using is probably no longer valid . Try to log off kissanime addon. I'm going to change the code base when I have time to try and fix the no playback issue in your case.

**Comment by joshlsmith** [comment]
I downloaded the march2017 update I'm using  kodi17.1 I click on a episode but it doesn't bring up any links it looks like it's trying to find something but just stops

**Comment by gaining** [comment]
Kissanime seems to have made changes on their website again that would break the addon. Maybe new encryption algorithm, I'll have to investigate later.

**Comment by iamcubeman** [comment]
I'm on LibreElec with your March 2017 fixes zip. I can navigate through all the menus, but when I click on an episode, nothing happens. Any advice?

**Comment by djneo0** [comment]
I think the issue was fixed but somthing changed again

**Comment by jkj0019** [comment]
I Ann having the same problem as Joshlsmith, I downloaded the march2017 update I'm using kodi17.1  "I click on a episode but it doesn't bring up any links it looks like it's trying to find something but just stops" 

Is there any way to fix KissAnime or not? I am using a Fire Stick and need my anime supply back someone please help

**Comment by gaining** [comment]
I'm sorry guys, I'm just not working on this addon at the moment. I have been busy with other things.
