### ISSUE TITLE
KISSANIME ADDON VERSION 0.9.23 REFUSES TO WORK.!??!

### ISSUE THREAD

**Issue by ISSUES999** [gaining/Kissanime-fork#3]
I UPDATED THE ADDON AND STILL ITS NOT WORKING , I CANT GET TO THE RESOLUTION PAGES.

THE FAV4 IMAGE UPDATE OPENS A PAGE ? 

THE FAVORITES DONT OPEN AND KEEP ON LOADING FOR A LONG TIME TILL IT STOPS AND THAT CAUSES KODI TO CRUSH WHEN YOU TRY TO EXIT KODI I MEAN , I WAITED FOR TWENTY MINUTES SINCE KODI DOES THAT WHEN YOU SEARCH IN THE ADDON AND THE REFRESH PAGE CATCHES YOU IN THE SECONT TIME YOU USE THE SEARCH TAB AND IT ORIGINALY EXISTED.
DURING THE FIRST USE OF THE SEARCH TAB IT KICKS OUT OF THE ADDON.
THE KODI ERROR WAS "APPHANGB1"
DIDNT YOU RELEASE UN UPDATE LONG TIME AGO WHEN THE SITE WAS PLACING EITHER OPENLOAD SERVER OR STREAM SERVER AND SINCE HIGHWAY WAS BUSY U CREATED AN UPDATE THAT CONTAINED THE FAV4 IMAGE UPDATER OPTION , IT IS POSSIBLE THAT IT CREATES A PROBLEM WITH FAVORITES SINCE PEOPLE BACK THEN WERE REPORTING CRASHES BUT I DID NOT USE EITHER OF THEM BACK THEN , AND HIGHWAY99 MADE A REMARK ABOUT NEW FEATURES IN THE ADDON AND SOMETHING ABOUT NOT WANTING TO OMPOSE ANY FURTHER ON THE SITES OWNERS.!

**Comment by mark-netants** [comment]
Whats with the attitude ?

**Comment by ISSUES999** [comment]
ATTITUDE??????
AS FOR LOGS THAT WOULD MEAN GOING BACK TO THE ADDON AND RECREATE THE  KODI HANG , NO THANKS.
